_wandb:
    value:
        cli_version: 0.27.0
        e:
            c1umfshn9g5wmnfw41gwdhjwibomdwm7:
                codePath: scripts\sync_tensorboard_to_wandb.py
                codePathLocal: scripts\sync_tensorboard_to_wandb.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1997512130560"
                        used: "1717251248128"
                email: sandipanarnab@gmail.com
                executable: C:\Users\sandi\Desktop\ML Working Folder\crop_disease_detection\.venv\Scripts\python.exe
                git:
                    commit: 3ef7a838133ddfd06024dfa9d86dd0f073966697
                    remote: https://github.com/sandipan-ds/crop_disease_detection.git
                gpu: NVIDIA GeForce RTX 2060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1920
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060
                      uuid: GPU-462811f2-25ac-4e4c-6761-91874123a972
                host: Legion-B
                memory:
                    total: "25095901184"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\sandi\Desktop\ML Working Folder\crop_disease_detection\scripts\sync_tensorboard_to_wandb.py
                python: CPython 3.11.9
                root: C:\Users\sandi\Desktop\ML Working Folder\crop_disease_detection
                startedAt: "2026-06-03T15:55:58.121976Z"
                writerId: c1umfshn9g5wmnfw41gwdhjwibomdwm7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 15
                - 16
                - 34
                - 62
            "4": 3.11.9
            "5": 0.27.0
            "8":
                - 2
                - 3
            "10":
                - 21
            "12": 0.27.0
            "13": windows-amd64
batch_size:
    value: 128
dataset:
    value: PlantVillage + plant_dataset_2
dropout_fc:
    value: 0.5
epochs:
    value: 200
folds:
    value: 5
image_size:
    value: 224
initial_lr:
    value: 0.001
model_architecture:
    value: VGG16Transfer
model_name:
    value: vgg_16
model_size_mb:
    value: 456.35
num_classes:
    value: 102
optimizer:
    value: AdamW
param_count:
    value: 119629222
scheduler:
    value: ReduceLROnPlateau
test_images:
    value: 19167
training_images:
    value: 42006
weight_decay:
    value: 0.0001
